server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update  # Disable Hibernate DDL auto
    show-sql: true

# Flyway Configuration
#flyway:
 # enabled: true
  #locations: classpath:db/migration
