server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/appdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update #can lead to data loss in production
    show-sql: true